service: aerocene

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local

custom:
  scrapeTableName: 'scrape-table-${self:provider.stage}'
  requestTableName: 'request-table-${self:provider.stage}'
  instagramPostTableName: 'instagram-post-table-${self:provider.stage}'
  instagramCursorTableName: 'instagram-cursor-table-${self:provider.stage}'

  wsgi:
    app: app.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: non-linux
    zipImport: true

provider:
  name: aws
  runtime: python3.6
  timeout: 150
  region: us-east-2
  iamRoleStatements:
    # allow all actions on the posts table
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - { "Fn::GetAtt": ["InstagramPostDynamoDBTable", "Arn"] }
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - { "Fn::GetAtt": ["InstagramCursorDynamoDbTable", "Arn"] }
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - { "Fn::GetAtt": ["ScrapeDynamoDbTable", "Arn"] }
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - { "Fn::GetAtt": ["RequestDynamoDbTable", "Arn"] }

    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
  environment:
    SCRAPE_TABLE: ${self:custom.scrapeTableName}
    REQUEST_TABLE: ${self:custom.requestTableName}
    INSTAGRAM_POST_TABLE: ${self:custom.instagramPostTableName}
    INSTAGRAM_CURSOR_TABLE: ${self:custom.instagramCursorTableName}
    STAGE: ${self:provider.stage}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  # derp:
  #   handler: functions.derp
  scrapeStream:
    handler: functions.scrape_stream_handler
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          arn:
            Fn::GetAtt:
              - ScrapeDynamoDbTable
              - StreamArn
  trial:
    handler: functions.trial
  cron_launcher:
    handler: handler.cron_launcher
    events:
      - schedule: rate(1 minute)

resources:
  Resources:

    # a table to store requests made to the
    # adversarial server
    RequestDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.requestTableName}
        AttributeDefinitions:
          -
            AttributeName: address
            AttributeType: S
        KeySchema:
          -
            AttributeName: address
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    # a table to persist data
    # between lambda function executing scrapes
    ScrapeDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.scrapeTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    # a table to store cursors
    # scraped from instagram
    InstagramCursorDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.instagramCursorTableName}
        AttributeDefinitions:
          -
            # the string that stores the cursor
            AttributeName: cursor
            AttributeType: S
        KeySchema:
          -
            # we want these to be unique
            AttributeName: cursor
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

        # create a stream for this table
        StreamSpecification:
          # enable the stream
          # make it so that the handler receives
          # the old and new versions of each item
          StreamViewType: NEW_AND_OLD_IMAGES

    # a table to store posts
    # scraped from instagram
    InstagramPostDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.instagramPostTableName}
        AttributeDefinitions:
          -
            # the id of the post
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            # these should be unique
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
