service: aerocene

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  tableName: 'users-table-${self:provider.stage}'
  instagramUserTableName: 'instagram-users-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    zipImport: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["InstagramUsersDynamoDBTable", "Arn" ] }
  environment:
    USERS_TABLE: ${self:custom.tableName}
    INSTAGRAM_USERS_TABLE: ${self:custom.instagramUserTableName}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getUser:
    handler: wsgi.handler
    events:
      - http: 'GET /users/{proxy+}'



  createUser:
    handler: wsgi.handler
    events:
      - http: 'POST /users'
  posts:
    handler: wsgi.handler
    events:
      - http: 'POST /posts'
  hello:
    handler: functions.hello

  get_instagram_user:
    handler: functions.get_instagram_user

  get_user_posts:
    handler: functions.get_user_posts
  scrape_location:
    handler: functions.scrape_location

  createInstagramUser:
    handler: wsgi.handler
    events:
      - http: 'POST /instagram'

  getInstagramUser:
    handler: wsgi.handler
    events:
      - http: 'GET /instagram/{proxy+}'
  scrapeInstagramLocation:
    handler: wsgi.handler
    events:
      - http: 'GET /scrape/{proxy+}'

  scrapeInstagramLocationAtCursor:
    handler: wsgi.handler
    events:
      - http: 'GET /scrape_cursor/{proxy+}'

  scrapeInstagram:
    handler: wsgi.handler
    events:
      - http: 'GET /scrape_instagram'


resources:
  Resources:
    InstagramUsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.instagramUserTableName}

    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}


